# Generated by Django 6.0.3 on 2026-03-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_on',
            new_name='Date_of_purchase',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Item_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
